import os
from gptzero import GPTZero
from openai_detector import OpenAIDetector

# Utilisation de GPTZero

def detect_ai_gptzero(text: str) -> dict:
    """Retourne un score d'IA avec GPTZero (open source)"""
    detector = GPTZero()
    result = detector.check_text(text)
    return result

# Utilisation de OpenAI Detector

def detect_ai_openai(text: str) -> dict:
    """Retourne un score d'IA avec OpenAI Detector (open source)"""
    detector = OpenAIDetector()
    result = detector.check_text(text)
    return result

# Exemple d'utilisation
if __name__ == "__main__":
    sample = "This is a test sentence generated by an AI language model."
    print("GPTZero:", detect_ai_gptzero(sample))
    print("OpenAI Detector:", detect_ai_openai(sample))
